//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPSite {
    
    
    public partial class Default {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// StageOne_CheckBox_ShowPriceUpdates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowPriceUpdates;
        
        /// <summary>
        /// TextBox_ProductName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_ProductName;
        
        /// <summary>
        /// TextBox_StartDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_StartDate;
        
        /// <summary>
        /// TextBox_StartTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_StartTime;
        
        /// <summary>
        /// TextBox_EndDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_EndDate;
        
        /// <summary>
        /// TextBox_EndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_EndTime;
        
        /// <summary>
        /// TextBox_Seconds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_Seconds;
        
        /// <summary>
        /// StageOne_CheckBox_ShowNewsUpdates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowNewsUpdates;
        
        /// <summary>
        /// StageOne_CheckBox_ShowSentimentMinus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowSentimentMinus;
        
        /// <summary>
        /// StageOne_CheckBox_ShowSentimentPlus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowSentimentPlus;
        
        /// <summary>
        /// StageOne_CheckBox_ShowPriceJumps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowPriceJumps;
        
        /// <summary>
        /// TextBox_PriceChangedPositive_THRESHHOLD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_PriceChangedPositive_THRESHHOLD;
        
        /// <summary>
        /// StageOne_CheckBox_ShowPriceFalls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowPriceFalls;
        
        /// <summary>
        /// TextBox_PriceChangedNegative_THRESHHOLD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_PriceChangedNegative_THRESHHOLD;
        
        /// <summary>
        /// StageOne_CheckBox_ShowNewsStories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowNewsStories;
        
        /// <summary>
        /// StageOne_CheckBox_ShowNewsUpdatePlus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowNewsUpdatePlus;
        
        /// <summary>
        /// TextBox_PriceChangedPositiveWithNewsUpdate_THRESHHOLD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_PriceChangedPositiveWithNewsUpdate_THRESHHOLD;
        
        /// <summary>
        /// StageOne_CheckBox_ShowNewsUpdateMinus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowNewsUpdateMinus;
        
        /// <summary>
        /// TextBox_PriceChangedNegativeWithNewsUpdate_THRESHHOLD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_PriceChangedNegativeWithNewsUpdate_THRESHHOLD;
        
        /// <summary>
        /// StageOne_CheckBox_ShowNewsStoryPlus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowNewsStoryPlus;
        
        /// <summary>
        /// StageOne_CheckBox_ShowNewsStoryMinus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox StageOne_CheckBox_ShowNewsStoryMinus;
        
        /// <summary>
        /// Button_GetData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_GetData;
        
        /// <summary>
        /// Button_ShowAllEvents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_ShowAllEvents;
        
        /// <summary>
        /// Button_ShowIndividualEvent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_ShowIndividualEvent;
        
        /// <summary>
        /// Button_ShowIndividualEventWithSubEvents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_ShowIndividualEventWithSubEvents;
        
        /// <summary>
        /// Button_SaveOverlay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_SaveOverlay;
        
        /// <summary>
        /// ShowAIO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ShowAIO1;
    }
}
